CREATE SEQUENCE  "SICLE"."SEQ_TB_ERROR"  MINVALUE 1 MAXVALUE 999999999999999999999999999 
INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
   
  CREATE TABLE "SICLE"."TB_ERROR" 
   (	"ID" NUMBER(38,0) NOT NULL ENABLE, 
	"MESSAGE" VARCHAR2(100 BYTE) NOT NULL ENABLE, 
	"INNEREXCEPTION" VARCHAR2(2000 BYTE), 
  "STACKTRACE" VARCHAR2(2000 BYTE), 
	"OCCURRENCE" DATE NOT NULL ENABLE, 
	"USERNAME" VARCHAR2(8 BYTE) NOT NULL ENABLE,
	"ERRORTYPE" NUMBER(*,0) NOT NULL ENABLE, 
	 CONSTRAINT "TB_ERROR_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "SICLE_DATA"  ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SICLE_DATA" ;

CREATE OR REPLACE TRIGGER "SICLE"."TB_ERROR_TRG" 
BEFORE INSERT ON TB_ERROR 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID IS NULL THEN
      SELECT SEQ_TB_ERROR.NEXTVAL INTO :NEW.ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "SICLE"."TB_ERROR_TRG" ENABLE;
commit;